spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 111111
    url: jdbc:mysql://192.168.110.4:3306/mall?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
  rabbitmq:
    addresses: 192.168.110.4
    port: 5672
    username: guest
    password: guest
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    # 控制台日志配置
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mappers/*.xml
logging:
  pattern:
    console: "[%thread] %-5level %logger{36} - %msg%n"
server:
  port: 8080
  servlet:
    session:
      timeout: 120
